version: '3'
services:
  flask:
    restart: always
    build: .
    env_file:
      - prod.env
    ports:
     - "5000:5000"
    volumes:
     - .:/app
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
